import {
  InputObject,
  TextInputProps,
  INPUT_TYPES,
  TEXT_INPUT_SIZE,
} from "@/components";
import { Kin } from "@/modules/MyBio/models/Kin";
export const KinBenInfo = (kin?: Kin) => {
  return [
    {
      id: "firstName",
      label: "First Name",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      defaultValue: kin?.firstName,
      required: true,
      placeholder: "FirstName",
    },
    {
      id: "lastName",
      label: "Last Name",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      defaultValue: kin?.lastName,
      required: true,
      placeholder: "FirstName LastName",
    },
    {
      id: "gender",
      label: "Gender",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.dropdown,
      items: ["Select a Gender", "Female", "Male"],
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.sex,
      required: true,
    },
    {
      id: "relationship",
      label: "Relationship",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.dropdown,
      items: [
        "Select a Relationship",
        "Child",
        "Parent",
        "Spouse",
        "Sibling",
        "Partner",
        "Unspecified",
      ],
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.relationship,
      required: true,
    },
    {
      id: "address",
      label: "Address",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.address,
      editMode: true,
      copy: "",
      placeHolder: "",
      disabled: true,
      setShowError: () => {},
      setValue: () => {},
      required: true,
    },
    // {
    //   id: "addressState",
    //   label: "State",
    //   setValue: () => {},
    //   span: TEXT_INPUT_SIZE.span1,
    //   style: INPUT_TYPES.dropdown,
    //   editMode: true,
    //   items: ["Lagos", "Abuja", "Rivers"],
    //   copy: "",
    //   setShowError: () => {},
    //   defaultValue: kin.contactDetails?.permanentAddress?.state,
    // },
    // {
    //   id: "addressCountry",
    //   label: "Country",
    //   setValue: () => {},
    //   span: TEXT_INPUT_SIZE.span1,
    //   style: INPUT_TYPES.dropdown,
    //   items: ["Nigeria", "Canada", "US", "Ghana"],
    //   editMode: true,
    //   copy: "",
    //   setShowError: () => {},
    //   defaultValue: "Nigeria",
    // },
    {
      id: "mobile",
      label: "Mobile Number",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.phone,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.mobile,
      required: true,
    },
    {
      id: "email",
      label: "Email Address",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.email,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.email,
    },
    {
      id: "percentage",
      label: "Percentage",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.number,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.percentage,
      required: true,
    },
    {
      id: "dateOfBirth",
      label: "Date of Birth",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.date,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: kin?.dateOfBirth,
      required: true,
    },
  ];
};
