import {
  InputObject,
  TextInputProps,
  INPUT_TYPES,
  TEXT_INPUT_SIZE,
} from "@/components";
import { Person } from "@/models/Person";
export const UserInputModel = (person?: Person) => {
  return [
    {
      id: "firstName",
      label: "First Name",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      defaultValue: person?.firstName,
      required: true,
      placeHolder: "Enter your First Name",
    },
    {
      id: "middleName",
      label: "Middle Name",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      // defaultValue: person?.firstName,
      required: true,
      placeholder: "Enter your Middle Name",
    },
    {
      id: "lastName",
      label: "Last Name",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      defaultValue: person?.lastName,
      required: true,
      placeholder: "Enter your Last name",
    },

    {
      id: "phone",
      label: "Phone Number",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.phone,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.phone,
      required: true,
    },
    {
      id: "email",
      label: "Email Address",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.email,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.email,
    },
    {
      id: "licenseNumber",
      label: "License Number",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.number,
      required: true,
    },
    {
      id: "licenseClass",
      label: "License Class",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.class,
      required: true,
    },
    {
      id: "licenseStart",
      label: "License Start",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.date,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.expirationDate,
      required: true,
    },
    {
      id: "licenseEnd",
      label: "License End",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.date,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.expirationDate,
      required: true,
    },
    {
      id: "licenseEnd",
      label: "License End",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.expirationDate,
      required: true,
    },
    {
      id: "staffID",
      label: "Employee ID",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.licenseInformation?.expirationDate,
      required: true,
    },
    {
      id: "jobTitle",
      label: "Job Title",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.phone,
      editMode: true,
      copy: "",
      setShowError: () => {},
      defaultValue: person?.phone,
      required: true,
    },
  ];
};
