import {
  InputObject,
  TextInputProps,
  INPUT_TYPES,
  TEXT_INPUT_SIZE,
} from "@/components";
import { Vehicle } from "@/models";
import { Person } from "@/models/Person";
export const DefaultVehicleInputFields = (vehicle?: Vehicle) => {
  return [
    {
      id: "manufacturer",
      label: "Manufacturer",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.combo,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      // defaultValue: vehicle?.firstName,
      required: true,
      placeHolder: "Enter your First Name",
    },
    {
      id: "model",
      label: "Model",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.combo,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      required: false,
      placeholder: "Enter your Middle Name",
    },
    {
      id: "trim",
      label: "Trim",
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.combo,
      editMode: true,
      copy: "",
      setValue: () => {},
      setShowError: () => {},
      required: true,
      placeholder: "Enter your Last name",
    },

    {
      id: "year",
      label: "Year",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.number,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.phone,
      required: true,
    },
    {
      id: "name",
      label: "Name (Optional)",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      placeholder: "e.g., CEO Suite Utility Sedan",
      setShowError: () => {},
      // defaultValue: person?.email,
      disabled: false,
    },
    {
      id: "licenseNumber",
      label: "License Number",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.licenseInformation?.number,
      required: false,
    },
    {
      id: "vin",
      label: "Vehicle Identification Number (VIN)",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.licenseInformation?.class,
      required: true,
    },
    {
      id: "type",
      label: "Type",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.text,
      editMode: true,
      copy: "",
      setShowError: () => {},
      required: true,
    },
    {
      id: "color",
      label: "Color",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.combo,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.licenseInformation?.expirationDate,
      required: false,
    },
    {
      id: "baseMileage",
      label: "Starting Mileage",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.number,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.licenseInformation?.expirationDate,
      required: false,
    },
    {
      id: "energyType",
      label: "Energy Type",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.combo,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.licenseInformation?.expirationDate,
      required: true,
    },
    {
      id: "image",
      label: "Image",
      setValue: () => {},
      span: TEXT_INPUT_SIZE.span1,
      style: INPUT_TYPES.phone,
      editMode: true,
      copy: "",
      setShowError: () => {},
      // defaultValue: person?.phone,
      required: false,
    },
  ];
};
